[tool.ruff]
line-length = 120
ident-with = 4
target-version = 'py311'

[tool.ruff.lint.extend-pre-file-ignores]
"__init__.py" = ["f401"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "B", "I"]
fixable = ["ALL"]

[tool.ruff.format]
line-ending = "auto"
quote-style = "double"
ident-style = "space"

[tool.pytest.ini_option]
DJANGO_SETTINGS_MODULE = 'core.settings.test'
python_files = ["test_*.py", "_test.py", "tests.py"]
addopts = "-v"
paythonpath=["recipe_api"]