name: recipe_api_local

services:

  postgres:
    container_name: recipe_api_local_postgres
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"

  django:
    container_name: recipe_api_local_django
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - main
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: on-failure

networks:
  main:

volumes:
  postgres_data: {}
