# Generated by Django 5.1.2 on 2024-10-22 05:19

from django.db import migrations, models

import recipes.models.recipe


class Migration(migrations.Migration):
    dependencies = [
        ("ingredients", "0001_initial"),
        ("recipes", "0002_recipe_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(null=True, upload_to=recipes.models.recipe.recipe_image_file_path),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(to="ingredients.ingredient"),
        ),
    ]
