name: test

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python and cache dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: "pip"
          cache-dependency-path: "recipe_api/requirements/*.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r recipe_api/requirements/local.txt

      - name: Run tests
        run: pytest
        env:
          SECRET_KEY: "django-insecure-px10t#3!v8!svg#y-d(r7gmwrl-*z5wctywbztooo#zl+-0*hm"
          DB_NAME: recipe_test
          DB_USER: test
          DB_PASSWORD: test
          DB_HOST: default
          DB_PORT: 5432
